name: desafio_gen
description: Projeto Gen Desafio Marvel.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  icons_launcher: ^2.0.6
  flutter_native_splash: ^2.2.16
  lottie: ^2.2.0
  http: ^0.13.5
  syncfusion_flutter_charts: ^20.4.49
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  rename: ^2.1.1

flutter:
  uses-material-design: true
  assets:
    - assets/